{{/*
Deploy the RDP Gateway if .Values.kasmApp.servicesToDeploy.rdpGateway.deploy set to true
*/}}
{{- if .Values.kasmApp.servicesToDeploy.rdpGateway.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kasmApp.servicesToDeploy.rdpGateway.name }}-deployment
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.kasmApp.servicesToDeploy.rdpGateway.name }}
    {{- include "kasm.defaultLabels" . | indent 4 }}
spec:
  replicas: {{ .Values.kasmApp.servicesToDeploy.rdpGateway.replicas | default (include "replicas.preset" (dict "node" "rdp" "size" .Values.kasmApp.deploymentSize)) }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: {{ add1 (.Values.kasmApp.servicesToDeploy.rdpGateway.replicas | default (include "replicas.preset" (dict "node" "rdp" "size" .Values.kasmApp.deploymentSize))) }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.kasmApp.servicesToDeploy.rdpGateway.name }}
  template:
    metadata:
      labels:
        kasm_role: rdpGateway
        app.kubernetes.io/name: {{ .Values.kasmApp.servicesToDeploy.rdpGateway.name }}
        {{- include "kasm.defaultLabels" . | indent 8 }}
    spec:
      restartPolicy: {{ .Values.global.image.restartPolicy }}
      {{- if .Values.global.image.pullSecrets }}
        {{- include "image.pullSecrets" . | indent 6 }}
      {{- end }}
      {{- if .Values.kasmApp.applyHardening }}
        {{- include "kasm.podSecurity" . | indent 6 }}
      {{- end }}
      initContainers:
        {{- if .Values.kasmApp.applyHardening }}
          {{- include "rdpGateway.podSecurity.initContainer" . | indent 8 }}
          {{- include "rdpGateway.podSecurity.mounts" . | indent 12 }}
        {{- end }}
        {{- include "kasm.apiWaitContainer" . | indent 8 }}
        {{- if .Values.kasmApp.applyHardening }}
          {{- include "kasm.containerSecurity" . | indent 10 }}
        {{- end }}
      containers:
        - name: {{ .Values.kasmApp.servicesToDeploy.rdpGateway.name }}-container
          image: "{{ .Values.kasmApp.servicesToDeploy.rdpGateway.image }}:{{ .Values.kasmApp.servicesToDeploy.rdpGateway.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          env:
            - name: SERVER_ZONE_NAME
              value: {{ .Values.kasmApp.zoneName | default "default" }}
            - name: REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.kasmApp.name | default "kasm" }}-secrets
                  key: service-token
          ports:
            - name: {{ .Values.kasmApp.servicesToDeploy.rdpGateway.name }}-pt
              containerPort: 5555
              protocol: TCP
          {{- if .Values.kasmApp.servicesToDeploy.rdpGateway.addHealthChecks }}
          livenessProbe:
            {{- include "health.tcp" (dict "portName" (printf "%s-pt" .Values.kasmApp.servicesToDeploy.rdpGateway.name) ) | indent 12 }}
          {{- end }}
          {{- if .Values.kasmApp.servicesToDeploy.rdpGateway.addHealthChecks }}
          readinessProbe:
            {{- include "health.http" (dict "path" "/__healthcheck" "portName" (printf "%s-pt" .Values.kasmApp.servicesToDeploy.rdpGateway.name) ) | indent 12 }}
          {{- end }}
          {{- if .Values.kasmApp.servicesToDeploy.rdpGateway.resources }}
          resources: {{- toYaml .Values.kasmApp.servicesToDeploy.rdpGateway.resources | nindent 12 }}
          {{- else }}
          resources: {{- include "resources.preset" (dict "node" "rdp" "size" .Values.kasmApp.deploymentSize) | nindent 12 }}
          {{- end }}
          {{- if .Values.kasmApp.applyHardening }}
            {{- include "kasm.containerSecurity" . | indent 10 }}
          {{- end }}
          volumeMounts:
            - name: rdp-proxy-cert
              mountPath: /usr/local/etc/rdpproxy/rdpproxy.crt
              subPath: tls.crt
            - name: rdp-proxy-cert
              mountPath: /usr/local/etc/rdpproxy/rdpproxy.key
              subPath: tls.key
            {{- if .Values.kasmApp.applyHardening }}
              {{- include "rdpGateway.podSecurity.mounts" . | indent 12 }}
            {{- end }}
      volumes:
        - name: rdp-proxy-cert
          secret:
            secretName: {{ .Values.kasmCerts.rdpGateway.name }}
        {{- if .Values.kasmApp.applyHardening }}
          {{- include "rdpGateway.podSecurity.volumes" . | indent 8 }}
        {{- end }}
  {{- if .Values.kasmApp.applyHardening }}
    {{- include "rdpGateway.podSecurity.pvc" . }}
  {{- end }}
{{ include "kasm.serviceTemplate" (list . "rdp-gateway" .Values.kasmApp.servicesToDeploy.rdpGateway.name (list "5555" 3389) ) }}
{{- end }}