{{- define "guac.podSecurity.initContainer" }}
- name: guac-tmp-perms
  image: busybox
  imagePullPolicy: IfNotPresent
  command:
    - /bin/sh
    - -ec
    - |
      echo "Setting permissions and ownership for /tmp..." && chown -R 1000:1000 /tmp && chmod -R 777 /tmp
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
{{- end }}

{{- define "guac.podSecurity.mounts" }}
volumeMounts:
  - name: kasm-guac-data
    mountPath: /tmp
{{- end }}

{{- define "guac.podSecurity.volumes" }}
volumes:
  - name: kasm-guac-data
    persistentVolumeClaim:
      claimName: {{ .Values.kasmApp.servicesToDeploy.kasmGuac.name }}-pvc
{{- end }}

{{- define "guac.podSecurity.pvc" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.kasmApp.servicesToDeploy.kasmGuac.name }}-pvc
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.kasmApp.servicesToDeploy.kasmGuac.name }}-pvc
    {{- include "kasm.defaultLabels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
{{- end }}
