{{/*
Deploy the Guacamole Web RDP if .Values.kasmApp.servicesToDeploy.kasmGuac.deploy set to true
*/}}
{{- if .Values.kasmApp.servicesToDeploy.kasmGuac.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kasmApp.servicesToDeploy.kasmGuac.name }}-deployment
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.kasmApp.servicesToDeploy.kasmGuac.name }}
    {{- include "kasm.defaultLabels" . | indent 4 }}
spec:
  replicas: {{ .Values.kasmApp.servicesToDeploy.kasmGuac.replicas | default (include "replicas.preset" (dict "node" "guac" "size" .Values.kasmApp.deploymentSize)) }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: {{ add1 (.Values.kasmApp.servicesToDeploy.kasmGuac.replicas | default (include "replicas.preset" (dict "node" "guac" "size" .Values.kasmApp.deploymentSize))) }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.kasmApp.servicesToDeploy.kasmGuac.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.kasmApp.servicesToDeploy.kasmGuac.name }}
        {{- include "kasm.defaultLabels" . | indent 8 }}
    spec:
      restartPolicy: {{ .Values.global.image.restartPolicy }}
      {{- if .Values.global.image.pullSecrets }}
        {{- include "image.pullSecrets" . | indent 6 }}
      {{- end }}
      {{- if .Values.kasmApp.applyHardening }}
        {{- include "kasm.podSecurity" . | indent 6 }}
      {{- end }}
      initContainers:
        {{- if .Values.kasmApp.applyHardening }}
          {{- include "guac.podSecurity.initContainer" . | indent 8 }}
          {{- include "guac.podSecurity.mounts" . | indent 10 }}
        {{- end }}
        {{- include "kasm.apiWaitContainer" . | nindent 8 }}
        {{- if .Values.kasmApp.applyHardening }}
          {{- include "kasm.containerSecurity" . | indent 10 }}
        {{- end }}
      containers:
        - name: {{ .Values.kasmApp.servicesToDeploy.kasmGuac.name }}-container
          image: "{{ .Values.kasmApp.servicesToDeploy.kasmGuac.image }}:{{ .Values.kasmApp.servicesToDeploy.kasmGuac.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          env:
            - name: CLUSTER_SIZE
              value: "4"
            - name: REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.kasmApp.name | default "kasm" }}-secrets
                  key: service-token
            - name: ZONE
              value: default
          ports:
            - name: {{ .Values.kasmApp.servicesToDeploy.kasmGuac.name }}-port
              containerPort: 3000
              protocol: TCP
          {{- if .Values.kasmApp.servicesToDeploy.kasmGuac.addHealthChecks }}
          livenessProbe:
            {{- include "health.tcp" (dict "port" (printf "%s-port" .Values.kasmApp.servicesToDeploy.kasmGuac.name)) | indent 12 }}
          {{- end }}
          {{- if .Values.kasmApp.servicesToDeploy.kasmGuac.addHealthChecks }}
          readinessProbe:
            {{- include "health.command" (dict "command" "curl http://localhost:3000/__healthcheck") | indent 12 }}
          {{- end }}
          {{- if .Values.kasmApp.servicesToDeploy.kasmGuac.resources }}
          resources: {{- toYaml .Values.kasmApp.servicesToDeploy.kasmGuac.resources | nindent 12 }}
          {{- else }}
          resources: {{- include "resources.preset" (dict "node" "guac" "size" .Values.kasmApp.deploymentSize) | nindent 12 }}
          {{- end }}
          {{- if .Values.kasmApp.applyHardening }}
            {{- include "kasm.containerSecurity" . | indent 10 }}
          {{- end }}
          {{- if .Values.kasmApp.applyHardening }}
            {{- include "guac.podSecurity.mounts" . | indent 10 }}
            {{- include "guac.podSecurity.volumes" . | indent 6 }}
          {{- end }}
  {{- if .Values.kasmApp.applyHardening }}
    {{- include "guac.podSecurity.pvc" . }}
  {{- end }}
{{- end }}
{{ include "kasm.serviceTemplate" (list . "kasm-guac" .Values.kasmApp.servicesToDeploy.kasmGuac.name (list 3000 3001 3002 3003 3004) ) }}
