{{- define "proxy.podSecurity.initContainer" }}
- name: proxy-data-perms
  image: busybox
  imagePullPolicy: IfNotPresent
  command:
    - /bin/sh
    - -ec
    - |
      echo "Setting permissions and ownership for /var/cache/nginx..." && chown -R 1000:1000 /var/cache/nginx && chmod -R 755 /var/cache/nginx
      echo "Setting permissions and ownership for /var/log/external/nginx..." && chown -R 1000:1000 /var/log/external/nginx && chmod -R 755 /var/log/external/nginx
      echo "Setting permissions and ownership for /tmp..." && chmod -R 777 /tmp
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
  volumeMounts:
{{- end }}

{{- define "proxy.podSecurity.mounts" }}
- name: kasm-proxy-data
  mountPath: /var/cache/nginx
- name: kasm-proxy-data
  mountPath: /var/log/external/nginx
- name: kasm-proxy-data
  mountPath: /run
{{- end }}

{{- define "proxy.podSecurity.volumes" }}
- name: kasm-proxy-data
  persistentVolumeClaim:
    claimName: {{ .Values.kasmApp.servicesToDeploy.kasmProxy.name }}-pvc
{{- end }}

{{- define "proxy.podSecurity.pvc" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.kasmApp.servicesToDeploy.kasmProxy.name }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.kasmApp.servicesToDeploy.kasmProxy.name }}-pvc
{{- include "kasm.defaultLabels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
{{- end }}