{{- define "rdpHttpsGateway.podSecurity.initContainer" }}
- name: rdp-https-gateway-tmp-perms
  image: busybox
  imagePullPolicy: IfNotPresent
  command:
    - /bin/sh
    - -ec
    - |
      echo "No customizations needed yet."
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
  volumeMounts:
{{- end }}

{{- define "rdpHttpsGateway.podSecurity.mounts" }}
- name: kasm-rdp-https-gateway-data
  mountPath: /opt/kasm/current/log
- name: kasm-rdp-https-gateway-data
  mountPath: /tmp
{{- end }}

{{- define "rdpHttpsGateway.podSecurity.volumes" }}
- name: kasm-rdp-https-gateway-data
  persistentVolumeClaim:
    claimName: {{ .Values.kasmApp.servicesToDeploy.rdpHttpsGateway.name }}-pvc
{{- end }}

{{- define "rdpHttpsGateway.podSecurity.pvc" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.kasmApp.servicesToDeploy.rdpHttpsGateway.name }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.kasmApp.servicesToDeploy.rdpHttpsGateway.name }}-pvc
    {{- include "kasm.defaultLabels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
{{- end }}
