global: {}

namespace: kasm-helm

serviceAccount:
  create: true
  labels: {}
  annotations: {}
  autoMount: true
  imagePullSecrets:
  - regcred

#---------------------------------
# Host name used by nginx and ingress
#---------------------------------
host: kasm.home.lab

kasmApp:
  extraLabels: {}
  annotations: {}
  replicas: 1
  name: kasm # Name of deployment 
  nodeSelector: {}

## Kasm passwords to use at runtime
## If values below are not provided, Helm will dynamically generate them. You can find the initial passwords
## in the Deployment Namespace > Secrets > kasm-secrets
## TODO: Consider actual encrypted secrets using some other secrets management process
redisPassword: ""
dbPassword: ""
managerToken: ""
serviceToken: ""
adminPassword: "" 
userPassword: ""