global: {}

namespace: kasm-helm

serviceAccount:
  create: true
  labels: {}
  annotations: {}
  autoMount: true
  imagePullSecrets:
  - regcred

#---------------------------------
# Host name used by nginx and ingress
#---------------------------------
host: kasm.home.lab

kasmApp:
  extraLabels: {}
  annotations: {}
  replicas: 1
  name: kasm # Name of deployment 
  nodeSelector: {}
