global: {}

namespace: kasm-helm

serviceAccount:
  create: true
  labels: {}
  annotations: {}
  autoMount: true
  imagePullSecrets:
    - regcred

#------------------------------------------------
# A list of Hostnames used by nginx and ingress
#------------------------------------------------
hostnames:
  - kasm.home.lab

kasmApp:
  name: kasm # Name of deployment 
  extraLabels: {}
  annotations: {}
  nodeSelector: {}
  certs:
    - proxy
    - rdpproxy

## Kasm service replica counts
apiReplicas: 3
managerReplicas: 2
proxyReplicas: 2
guacReplicas: 1
rdpGatewayReplicas: 1
shareReplicas: 1

## Kasm passwords to use at runtime
## If values below are not provided, Helm will dynamically generate them. You can find the initial passwords
## in the Deployment Namespace > Secrets > kasm-secrets
## TODO: Consider actual encrypted secrets using some other secrets management process
kasmPasswords:
  redis-password: ""
  db-password: ""
  manager-token: ""
  service-token: ""
  admin-password: "" 
  user-password: ""