global: {}

namespace: kasm-helm

## Container pull settings
imagePullSecrets: regcred
imagePullPolicy: Always

#------------------------------------------------
# A list of Hostnames used by nginx and ingress
#------------------------------------------------
hostnames:
  - kasm.home.lab
  - "*.kasm.home.lab"

kasmApp:
  name: kasm # Name of deployment 
  ## Kasm service replica counts
  apiReplicas: 3
  managerReplicas: 2
  proxyReplicas: 2
  guacReplicas: 1
  rdpGatewayReplicas: 1
  shareReplicas: 1
  certs:
    - name: nginx-proxy-cert
      create: true
      cert: |-
        ######    Place public SSL Cert here     ######
        ######  Leave empty for Helm to generate ######
      key: |-
        ######    Place public SSL Key here      ######
        ######  Leave empty for Helm to generate ######
    - name: rdpproxy-cert
      create: true
      cert: |-
        ######   Place RDP Proxy SSL Cert here   ######
        ######  Leave empty for Helm to generate ######
      key: |-
        ######   Place RDP Proxy SSL Key here    ######
        ######  Leave empty for Helm to generate ######

## Kasm passwords to use at runtime
## If values below are not provided, Helm will dynamically generate them. You can find the initial passwords
## in the Deployment Namespace > Secrets > "kasm app name"-secrets
## TODO: Consider actual encrypted secrets using some other secrets management process
kasmPasswords:
  redisPassword: ""
  dbPassword: ""
  managerToken: ""
  serviceToken: ""
  adminPassword: "" 
  userPassword: ""