apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kasmApp.name | default "kasm" }}-api
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    kasm_app: {{ .Values.kasmApp.name | default "kasm" }}-api
{{- include "kasm.defaultLabels" . | indent 4 }}
spec:
  replicas: {{ .Values.kasmApp.apiReplicas }}
  selector:
    matchLabels:
      kasm_app: {{ .Values.kasmApp.name | default "kasm" }}-api
  template:
    metadata:
      labels:
        kasm_app: {{ .Values.kasmApp.name | default "kasm" }}-api
{{- include "kasm.defaultLabels" . | indent 8 }}
    spec:
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
{{- end }}
      initContainers:
        - name: db-is-ready
          image: kasmweb/api-private:feature_KASM-5313_webui_code_move
          imagePullPolicy: {{ .Values.imagePullSecrets }}
          env:
            - name: DB_AUTO_INITIALIZE
              value: "false"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.kasmApp.name | default "kasm" }}-secrets
                  key: db-password
            - name: START_SERVICES
              value: "false"
          command:
            - "/bin/bash"
            - "-c"
          args:
            - |
              while [ ! $(PGPASSWORD=$POSTGRES_PASSWORD psql -U kasmapp -d kasm -h db -t -c "select zone_id from zones" 2>/dev/null | wc -l) -ge 2 ]; do echo "Waiting for DB to initialize..."; sleep 5; done
      containers:
        - name: kasm-api
          image: kasmweb/api-private:feature_KASM-5313_webui_code_move
          imagePullPolicy: Always
          volumeMounts:
            - name: api-config
              mountPath: /opt/kasm/current/conf/app
          env:
            - name: DB_AUTO_INITIALIZE
              value: "false"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.kasmApp.name | default "kasm" }}-secrets
                  key: db-password
          resources: {}
      volumes:
        - name: api-config
          configMap:
            name: {{ .Values.kasmApp.name | default "kasm" }}-api-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: kasm-api
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
{{- include "kasm.defaultLabels" . | indent 4 }}
spec:
  selector:
    kasm_app: {{ .Values.kasmApp.name | default "kasm" }}-api
  ports:
  - name: kasm-api
    protocol: TCP
    port: 8080