apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kasm_app: kasm-api
    app: kasm
  name: kasm-api
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  replicas: 3
  selector:
    matchLabels:
      kasm_app: kasm-api
  template:
    metadata:
      labels:
        kasm_app: kasm-api
        app: kasm
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: db-init
          image: kasmweb/api-private:feature_KASM-5313_webui_code_move
          imagePullPolicy: Always
          env:
            - name: DB_AUTO_INITIALIZE
              value: "false"
            - name: POSTGRES_PASSWORD
              value: rSutQYTCMXrFzOdlQVDy
            - name: START_SERVICES
              value: "false"
          command:
            - "/bin/bash"
            - "-c"
          args:
            - |
              while [ ! $(PGPASSWORD=$POSTGRES_PASSWORD psql -U kasmapp -d kasm -h db -t -c "select zone_id from zones" 2>/dev/null | wc -l) -ge 2 ]; do echo "Waiting for DB to initialize..."; sleep 5; done
      containers:
        - name: kasm-api
          image: kasmweb/api-private:feature_KASM-5313_webui_code_move
          imagePullPolicy: Always
          env:
            - name: DB_AUTO_INITIALIZE
              value: "false"
            - name: POSTGRES_PASSWORD
              value: rSutQYTCMXrFzOdlQVDy
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kasm-api
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  selector:
    kasm_app: kasm-api
  ports:
  - name: kasm-api
    protocol: TCP
    port: 8080