{{- $altNames := list }}
{{- $certValue := "" }}
{{- $keyValue := "" }}
{{- $ca := genCA "kasm-ca" 365 }}
{{- range $certs := .Values.kasmApp.certs }}
  {{- if eq $certs.create true }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ $.Values.kasmApp.name | default "kasm" }}-{{ $certs.name }}
  namespace: {{ $.Values.namespace }}
  labels:
    kasm_app: {{ $.Values.kasmApp.name | default "kasm" }}-{{ $certs.name }}
{{- include "kasm.defaultLabels" $ | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    {{- if contains "SSL Cert here" $certs.cert }}
      {{- if contains "proxy" $certs.name }}
        {{- $altNames = $.Values.hostnames }}
      {{ else }}
        {{- $altNames = list "rdp-gateway" }}
      {{- end }}
      {{- $cert := genSignedCert ( first $.Values.hostnames | quote ) nil $altNames 365 $ca }}
      {{- $certValue = $cert.Cert }}
      {{- $keyValue = $cert.Key }}
    {{- else }}
      {{- $certValue = $certs.cert }}
      {{- $keyValue = $certs.key }}
    {{- end }}
data:
  tls.crt: {{ $certValue | b64enc }}
  tls.key: {{ $keyValue | b64enc }}
---
  {{- end }}
{{- end }}