{{- range $key, $value := .Values.kasmApp.certs }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.kasmApp.name | default "kasm" }}-{{ $value }}-cert
  namespace: 
  labels:
    kasm_app: {{ .Values.kasmApp.name | default "kasm" }}-{{ $value }}
{{- include "kasm.defaultLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{- if eq $value "proxy" }}
{{- $altNames := list .Values.hostnames }}
{{ else }}
{{- $altNames := list ( "rdp-gateway" ) }}
{{- end }}
{{- $ca := genCA "kasm-ca" 365 }}
{{- $cert := genSignedCert .Values.host nil $altNames 365 $ca }}
  {{ printf "%s%s" $value ".crt" }}: {{ $cert.Cert | b64enc }}
  {{ printf "%s%s" $value ".key" }}: {{ $cert.Key | b64enc }}
{{- end }}