apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.kasmApp.name }}-db-init
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    kasm_app: {{ .Values.kasmApp.name }}
{{- include "kasm.defaultLabels" . | indent 4 }}
spec:
  template:
    metadata:
      labels:
        kasm_app: {{ .Values.kasmApp.name | default "kasm" }}-api
{{- include "kasm.defaultLabels" . | indent 8 }}
    spec:
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
{{- end }}
      restartPolicy: OnFailure
      initContainers:
        - name: db-is-ready
          image: kasmweb/api-private:feature_KASM-5313_webui_code_move
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command:
            - "/bin/bash"
            - "-c"
          args:
            - |
              while ! pg_isready -h db -p 5432; do echo "Waiting for DB..."; sleep 5; done
      containers:
        - name: db-init
          image: kasmweb/api-private:feature_KASM-5313_webui_code_move
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          volumeMounts:
            - name: db-preseed-data
              mountPath: /opt/kasm/current/conf/database/seed_data
            - name: db-init-script
              mountPath: /usr/bin/startup.sh
              subPath: startup.sh
          env:
            - name: DB_AUTO_INITIALIZE
              value: "false"
            - name: DEFAULT_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.kasmApp.name | default "kasm" }}-secrets
                  key: admin-password
            - name: DEFAULT_MANAGER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.kasmApp.name | default "kasm" }}-secrets
                  key: manager-token
            - name: DEFAULT_REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.kasmApp.name | default "kasm" }}-secrets
                  key: service-token
            - name: DEFAULT_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.kasmApp.name | default "kasm" }}-secrets
                  key: user-password
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.kasmApp.name | default "kasm" }}-secrets
                  key: db-password
            - name: START_SERVICES
              value: "false"
          command:
            - "/bin/bash"
            - "-c"
          args:
            - |
              if [ ! $(PGPASSWORD=$POSTGRES_PASSWORD psql -U kasmapp -d kasm -h db -t -c "select zone_id from zones" 2>/dev/null | wc -l) -ge 2 ]; then export DB_AUTO_INITIALIZE="true"; fi
              if [[ "$DB_AUTO_INITIALIZE" == "true" ]]; then /usr/bin/startup.sh; else echo "DB already initialized."; fi
      volumes:
        - name: db-preseed-data
          configMap:
            name: {{ .Values.kasmApp.name | default "kasm" }}-db-init-configmap
        - name: db-init-script
          configMap:
            name: {{ .Values.kasmApp.name | default "kasm" }}-db-init-startup
            defaultMode: 0755
            