{{/*
Add Docker Login auth credentials
*/}}
{{- if .Values.global.image.pullCredentials }}
{{- $combined := printf "%s:%s" $.Values.global.image.pullCredentials.username $.Values.global.image.pullCredentials.password | b64enc -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.global.image.pullSecrets }}
  namespace: {{ $.Values.global.namespace | default $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $.Values.global.image.pullSecrets }}
    {{- include "kasm.defaultLabels" . | indent 4 }}
  annotations:
    helm.sh/hook: "pre-install"
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" $.Values.global.image.pullCredentials.registry $.Values.global.image.pullCredentials.username $.Values.global.image.pullCredentials.password $.Values.global.image.pullCredentials.email $combined | b64enc }}
{{- end }}