{{- if .Values.global.pullCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kasmApp.name | default "kasm" }}-docker-creds
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.kasmApp.name }}-docker-creds
    {{- include "kasm.defaultLabels" . | indent 4 }}
  annotations:
    helm.sh/hook: "pre-install"
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: {{ "{\"auths\": {\"{{ .Values.global.image.pullCredentials.registry }}\"}}:{\"username\": \"{{ .Values.global.image.pullCredentials.username }}\",\"password\":\"{{ .Values.global.image.pullCredentials.password }}\",\"email\":\"{{ .Values.global.image.pullCredentials.email }}\", \"auth\":\"{{ printf \"%s:%s\" .Values.global.image.pullCredentials.username .Values.global.image.pullCredentials.password }}\"}}" | b64enc }}
{{- end }}
