apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: {{ .Values.kasmApp.name | default "kasm" }}
  name: {{ .Values.kasmApp.name | default "kasm" }}-tls-ingress
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  tls:
  - hosts:
      - {{ .Values.host }}
    secretName: {{ .Values.kasmApp.name | default "kasm" }}-proxy-ingress-cert
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: kasm-api
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kasm-proxy
            port:
              number: 8080
      - path: /api/share/
        pathType: Prefix
        backend:
          service:
            name: kasm-share
            port:
              number: 8182