apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.kasmApp.name | default "kasm" }}-tls-ingress
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
{{- include "kasm.defaultLabels" . | indent 4 }}
spec:
  tls:
  - hosts:
      - {{ first .Values.hostnames }}
    secretName: {{ .Values.kasmApp.name | default "kasm" }}-proxy-cert
  rules:
  - host: {{ first .Values.hostnames }}
    http:
      paths:
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.kasmApp.name | default "kasm" }}-api
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.kasmApp.name | default "kasm" }}-proxy
            port:
              number: 8080
      - path: /api/share/
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.kasmApp.name | default "kasm" }}-share
            port:
              number: 8182