apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kasm_app: kasm-manager
  name: kasm-manager
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      kasm_app: kasm-manager
  strategy: {}
  template:
    metadata:
      labels:
        kasm_app: kasm-manager
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: api-is-ready
          image: kasmweb/manager-private:feature_KASM-5313_webui_code_move
          imagePullPolicy: Always
          command:
            - "/bin/bash"
            - "-c"
          args:
            - |
              while ! curl http://kasm-api:8080/api/__healthcheck 2>/dev/null | grep -q true; do echo "Waiting for the API server to start..."; sleep 5; done
      containers:
        - name: kasm-manager
          image: kasmweb/manager-private:feature_KASM-5313_webui_code_move
          imagePullPolicy: Always
          env:
            - name: POSTGRES_PASSWORD
              value: rSutQYTCMXrFzOdlQVDy
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kasm-manager
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  selector:
    kasm_app: kasm-manager
  ports:
  - name: kasm-manager
    protocol: TCP
    port: 8181