apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.kasmApp.name | default "kasm" }}
    kasm_app: {{ .Values.kasmApp.name | default "kasm" }}-share
  name: {{ .Values.kasmApp.name | default "kasm" }}-share
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  replicas: {{ .Values.shareReplicas }}
  selector:
    matchLabels:
      kasm_app: {{ .Values.kasmApp.name | default "kasm" }}-share
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.kasmApp.name | default "kasm" }}
        kasm_app: {{ .Values.kasmApp.name | default "kasm" }}-share
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: redis-is-ready
          image: redis:5-alpine
          imagePullPolicy: Always
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kasm-secrets
                  key: redis-password
            - name: REDIS_HOST
              value: kasm-redis
          command:
            - "/bin/sh"
            - "-c"
          args:
            - |
              while ! redis-cli -h $(REDIS_HOST) -p 6379 -a $(REDIS_PASSWORD) ping 2>/dev/null | grep -q PONG; do echo "Waiting for Redis to start..."; sleep 5; done
        - name: api-is-ready
          image: kasmweb/share-private:feature_KASM-5313_webui_code_move
          imagePullPolicy: Always
          command:
            - "/bin/bash"
            - "-c"
          args:
            - |
              while ! curl http://kasm-api:8080/api/__healthcheck 2>/dev/null | grep -q true; do echo "Waiting for the API server to start..."; sleep 5; done
      containers:
        - name: kasm-share
          image: kasmweb/share-private:feature_KASM-5313_webui_code_move
          imagePullPolicy: Always
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kasm-secrets
                  key: redis-password
            - name: REDIS_HOST
              value: kasm-redis
            - name: SHARE_ID
              value: auto
            - name: SERVER_HOSTNAME
              value: kasm-share
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kasm-secrets
                  key: db-password
          resources: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.kasmApp.name | default "kasm" }}
  name: kasm-share
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  selector:
    kasm_app: {{ .Values.kasmApp.name | default "kasm" }}-share
  ports:
  - name: kasm-share
    protocol: TCP
    port: 8182